### ISSUE TITLE
使用者若有多intend該如何處理

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#1]
你好，我想請教一下
如果user有多個intend時候該如何處理?
比如說我想去二二八公園公車票價調漲嗎?但我測試他正確來說應該要回 臺北市公共運輸處大眾運輸科
但似乎給出的事我想去二二八公園所對應的答案"臺北市政府文化局"
希望可以一起討論學習，謝謝

**Comment by p208p2002** [comment]
這樣應該是Multi-label Classification的方向
至於下面說會回答"臺北市政府文化局"我想是因為模型沒有理解到"公車票價"這一件事情
很有可能是訓練資料不足或是模型效能不佳導致
畢竟這個專案是屬於我的一個練習專案

在Multi-label Classification的部分huggingface目前並沒有提供對應的down-stream模型，這會是需要自己修改的部分，基本上會需要將原本的cross entropy loss改成binary cross entropy loss，這是因為多標籤實際上就是對每個標籤做是否分類

Multi-label Classification我自己還沒有深入了解，但是如果有問題的話我可以幫忙詢問

**Comment by p208p2002** [comment]
補充一個
也可以把每個標籤的機率都列出來
取top n，並且設立一個門檻值
這樣也可以達到多標籤分類的效果

**Comment by WenTingTseng** [comment]
你好，抱歉最近忙剛剛才注意到訊息
謝謝你的回應與建議
我會再研究一下
謝謝
