### ISSUE TITLE
關於Albert accuracy

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#2]
你好
最近看到您的更新多了Albert Model
想請教一下有關於Albert 在這個dataset上是否正確率有比BERT高呢?
因為我在我自己的dataset上，在BERT的accuracy是70%，但在Albert accuracy是23%
不太確定問題所在

**Comment by p208p2002** [comment]
你好
BERT模型在發表的時候根據隱藏層大小分別有base, large, xlarge

而albert為了比較也有上述三個版本，但是albert實際上為輕量版的bert，在參數量少了70%的情況下效能相比bert只有少了約一個百分點，亦即在相同的模型大小下albert是略遜於bert的

但是albert的優點在於有非常優異的模型拓展能力，有xxlarge版本,
bert則無法做到，所以論架構albert實際上是更優秀的，效能也比bert好非常多

補充一下，albert large的參數量甚至少於bert base

最後是關於我的程式碼，目前我還沒針對albert做進一步的調校，但是albert的表現應該是要更優於原本的bert

WenTingTseng <notifications@github.com> 於 2020年2月27日 週四 00:44 寫道：

**Comment by p208p2002** [comment]
關於你的實驗結果albert表現不如預期的原因可能是epoch或是lr需要在多調整，原本的參數是for bert的。另外要注意的是程式碼內置的是albert tiny，是非常迷你的模型，可以參閱readme下載更大的albert模型

**Comment by WenTingTseng** [comment]
OK，了解
我再研究一下
謝謝你~
