### ISSUE TITLE
關於Q和A對應關係如何找到

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#3]
你好:
我想請教一下您的程式中`tokenizer.build_inputs_with_special_tokens`中你只放了q進去。也就是只轉換成[CLS]Sentence_Q[SPE]形式。那這樣如何找到Q和A的對應關係，因為`BertForSequenceClassification`輸入形式不是應該是[CLS]Sentence_Q[SPE]sentence_A[SEP]這樣嗎

Thanks for your help

**Comment by p208p2002** [comment]
輸入格式與答案是分開的
[CLS]Sentence_Q[SPE]Sentence_A[SEP]只表達 Q 與 A具有上下文關係，並非答案
我個人更偏好這樣看
[CLS]Sentence_A[SPE]Sentence_B[SEP]
也就是說這是一個AB句的輸入，答案並不會在這裡提供

但是以這個repo的任務:文本分類(149類)
輸入僅有A句而已
所以輸入為[CLS]Sentence_A[SEP]
提供給model的答案會是你的類別id(數字)
> 在這個任務中是0-148

輸出格式為一個list
> 大小依據你設定有幾個類別
> 這個任務輸出長度是149的list

找到這個list最大數值的index
就會是預測結果id
我另外有寫一個[class](https://github.com/p208p2002/taipei-QA-BERT/blob/master/core.py#L46)處理id轉回text

舉例用到[CLS]Sentence_A[SPE]Sentence_B[SEP]的任務:
[SQuAD](https://rajpurkar.github.io/SQuAD-explorer/)
大致上是給定一段內文與問句然後回答問題
那他的輸入格式(根據[run_squad.py](https://github.com/huggingface/transformers/blob/master/examples/run_squad.py))就是
[CLS]Question[SEP]Context[SEP]
但是這個任務比較複雜，關於他的輸出跟如何decode有興趣可以再跟我討論^^
或是參考我的另一個[repo](https://github.com/p208p2002/bert-question-answer)

**Comment by p208p2002** [comment]
我最近剛好在製作關於這個repo的[教學投影片](https://github.com/p208p2002/taipei-QA-BERT/tree/master/tutorial)，可以參考一下
目前更新到ch3，預計下一周更新至ch4結束

投影片第22頁還有[predirt.py](https://github.com/p208p2002/taipei-QA-BERT/blob/master/predict.py#L46)，可以看到我如何處理QA的對應關係

**Comment by WenTingTseng** [comment]
好的，了解!
我會再研究一下你的投影片
Thanks
