### ISSUE TITLE
數據集

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#4]
請問您知道哪裡有類似像你這個project範例的數據集
像這種做成 分類問題FAQ的中文數據集呢

謝謝~

**Comment by p208p2002** [comment]
可以參考一下這個repo
https://github.com/CLUEbenchmark/CLUEDatasetSearch

ps. taipei-qa 這個數據集，其實是我的實驗室學長姐用爬蟲抓下來的

**Comment by WenTingTseng** [comment]
好的 了解，感謝分享

謝謝
