### ISSUE TITLE
關於TaipeiQA多Q對應1A 

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#5]
你好
我想向你請教一個問題，因為你的TaipeiQA是 多Q對應1A (一個answer當作一類，總共149類) 情況
如果在面對 非多Q1A 的情況，BERT可能就會很難 好得學習，這樣情況應該如何處理? 
謝謝

**Comment by p208p2002** [comment]
這個的話應該理想是朝向使用多選題的方法[bertformultiplechoice](https://huggingface.co/transformers/model_doc/bert.html#bertformultiplechoice)

官方有一些對應的[範例](https://huggingface.co/transformers/examples.html#multiple-choice)
不過最困難的地方應該還是在訓練資料的取得。

作為一種替代方案，我想應該可以直接看sequence classification的分類輸出，除了第一高的答案外，再設置一個門檻值(例如機率>0.7)，將那些高於門檻值的答案也輸出，做為多選題的答案

**Comment by WenTingTseng** [comment]
你好
替代方案設置一個門檻值將那些高於門檻值的答案也輸出，所以會輸出好幾個答案讓user去選這樣嗎?
但目前目標還是偏向說只輸出一個answer給user
我有在思考用兩層分類，第一層按照主題分 (EX:有14個主題就分14類)，假如說第 一層分到主題一然後主題一底下有20類就再往下分。
但是好像也一個問題這樣第二層要train好幾個BERT model?例如有14個主題就要有14個BERT分類模型

**Comment by p208p2002** [comment]
如果說是不想要train這麼多bert model的話可以考慮不同主題(domain)使用不同的linear layer，但是共用BERT

架構可能會像是
```
BERT -> doamin classifier(linear layer) -> [doamin classifier1(linear layer) ,doamin classifier2, ... doamin classifier n]
```
> BERT數量:1

而不是
```
Bert for sequence classification -> [Bert for sequence classification1, Bert for sequence classification2 , ... Bert for sequence classification n]
```
> BERT數量:n+1

※一般在使用huggingface/transformers的[BertForSequenceClassification](https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertForSequenceClassification)，其實是BERT模型後面在接一層linear layer做對應的下游任務，我想應該從這邊動手修改即可

**Comment by WenTingTseng** [comment]
你好:
方案一(BERT數量:1)我是懂你的意思但是不太確定程式要如何改?
BERT模型後面在接一層linear layer做對應的下游任務是指是指在
BertForSequenceClassification 中多加一層`self.classifier = nn.Linear(config.hidden_size, self.config.num_labels)`這個嗎

**Comment by p208p2002** [comment]
BertForSequenceClassification本來就幫你接好一層，應該是先用BertForSequenceClassification先分14類(主題)，然後後面加14個專屬那一主題的linear layer做細分
