### ISSUE TITLE
關於英文辨識

### ISSUE THREAD

**Issue by WenTingTseng** [p208p2002/taipei-QA-BERT#6]
你好，想請問一下這一套有辦法用在英文的資料上嗎?要如何更換,謝謝

**Comment by p208p2002** [comment]
可以在
https://github.com/p208p2002/taipei-QA-BERT/blob/master/train.py#L8
更換model setting使用的模型，換成"bert-base-uncase"就可以使用英文

然後替換訓練用資料
https://github.com/p208p2002/taipei-QA-BERT/blob/master/Taipei_QA_new.txt

這樣應該就可以work了


WenTingTseng <notifications@github.com> 於 2021年1月23日 週六 下午3:43寫道：

**Comment by p208p2002** [comment]
英文的vocab可以在這邊下載
https://huggingface.co/bert-base-uncased/tree/main


黃柏鈞 <p208p2002@gmail.com> 於 2021年1月25日 週一 上午11:02寫道：

**Comment by WenTingTseng** [comment]
OK 可以work了, 感謝
