### ISSUE TITLE
問答內容問題

### ISSUE THREAD

**Issue by leeprinxin** [p208p2002/taipei-QA-BERT#7]
請問我若輸入的問題是訓練集的其中一項，但我簡化這項問題或換句話說，是否也能達到同樣的回答?
因為我看到的預測檔案，好像只有用訓練集的問題

**Comment by p208p2002** [comment]
BERT是強大的預訓練模型，理論上是沒問題的

**Comment by leeprinxin** [comment]
> BERT是強大的預訓練模型，理論上是沒問題的

thanks.
